pipeline{
      agentany{
             stages ('build'){
                           steps{
                                sh ' echo " build successful " '
                                }
                               }
             stages ('test'){
                          steps{
                              sh ' echo " test the `hostname`" '
                               }
                            }



              }

         }  
            
        
          
